export const manufacturers = [
  {
    id: "1",
    name: "Apple",
    logo: require("@/assets/images/logopartners/logoApple.jpg"),
    category: "Téléphones",
  },
  {
    id: "2",
    name: "Samsung",
    logo: require("@/assets/images/logopartners/logoSamsung.jpg"),
    category: "Téléphones",
  },
  {
    id: "3",
    name: "HP",
    logo: require("@/assets/images/logopartners/logoHp.png"),
    category: "Ordinateurs",
  },
  {
    id: "4",
    name: "Dell",
    logo: require("@/assets/images/logopartners/logoDell.png"),
    category: "Ordinateurs",
  },
  {
    id: "5",
    name: "Lenovo",
    logo: require("@/assets/images/logopartners/logoLenovo.png"),
    category: "Ordinateurs",
  },
  {
    id: "6",
    name: "Asus",
    logo: require("@/assets/images/logopartners/logoAsus.png"),
    category: "Ordinateurs",
  },
  {
    id: "7",
    name: "Acer",
    logo: require("@/assets/images/logopartners/logoAcer.png"),
    category: "Ordinateurs",
  },
  {
    id: "8",
    name: "Microsoft",
    logo: require("@/assets/images/logopartners/logoMicrosoft.png"),
    category: "Logiciels",
  },
  {
    id: "9",
    name: "Sony",
    logo: require("@/assets/images/logopartners/logoSony.png"),
    category: "Électronique",
  },
  {
    id: "10",
    name: "Huawei",
    logo: require("@/assets/images/logopartners/logoHuawei.jpg"),
    category: "Téléphones",
  },
  {
    id: "11",
    name: "Brother",
    logo: require("@/assets/images/logopartners/logoBrother.png"),
    category: "Imprimantes",
  },
  {
    id: "12",
    name: "Canon",
    logo: require("@/assets/images/logopartners/logoCanon.png"),
    category: "Imprimantes",
  },
  {
    id: "13",
    name: "Epson",
    logo: require("@/assets/images/logopartners/logoEpson.jpg"),
    category: "Imprimantes",
  },
  {
    id: "14",
    name: "Honor",
    logo: require("@/assets/images/logopartners/logoHonor.png"),
    category: "Téléphones",
  },
  {
    id: "15",
    name: "LG",
    logo: require("@/assets/images/logopartners/logoLg.png"),
    category: "Téléphones",
  },
  {
    id: "16",
    name: "Oppo",
    logo: require("@/assets/images/logopartners/logoOppo.png"),
    category: "Téléphones",
  },
  {
    id: "17",
    name: "Realme",
    logo: require("@/assets/images/logopartners/logoRealme.png"),
    category: "Téléphones",
  },
  {
    id: "18",
    name: "Vivo",
    logo: require("@/assets/images/logopartners/logoVivo.png"),
    category: "Téléphones",
  },
  {
    id: "19",
    name: "Xerox",
    logo: require("@/assets/images/logopartners/logoXerox.png"),
    category: "Téléphones",
  },
  {
    id: "20",
    name: "Xioami",
    logo: require("@/assets/images/logopartners/logoXioami.png"),
    category: "Téléphones",
  },
];
